local STRINGS = GLOBAL.STRINGS

-- 自定义物品的实例,floatball
STRINGS.NAMES.FLOATBALL = "浮球"
--制作卡片上的描述示例，一行要小于9个字
STRINGS.RECIPE_DESC.FLOATBALL = "实际上没\n什么用处的球"
-- 示例武器，利爪
STRINGS.NAMES.SHARPCLAW = "利爪"
STRINGS.NAMES.ARCUEID = "爱尔奎特·布伦史塔德";
STRINGS.UI.CRAFTING.NEEDMOONCIRLEFORM = "使用第一具现原理制造\n解锁！";

--配方描述
--空间箱
STRINGS.RECIPE_DESC.BUILDING_ROOMBOX = "大箱子"
--魔术宝石冰箱
STRINGS.RECIPE_DESC.BUILDING_GEMICEBOX = "永久保鲜"
--旅行者时空箱
STRINGS.RECIPE_DESC.BUILDING_TRAVELLERBOX = "跨越空间,随用随取"
--宝石魔术灯
STRINGS.RECIPE_DESC.BUILDING_IMMORTALLIGHT = "驱散暗影"
--宝石发生器
STRINGS.RECIPE_DESC.BUILDING_GEMGENERATOR = "生产宝石"
--腐败滋生术式
STRINGS.RECIPE_DESC.BUILDING_ROTTENFORM = "加速腐败"
--第二分解术式
STRINGS.RECIPE_DESC.BUILDING_RECYCLEFORM ="分解物品"
--Infinitas箱
STRINGS.RECIPE_DESC.BUILDING_INFINITAS = "清理垃圾"
--魔术炮塔
STRINGS.RECIPE_DESC.BUILDING_GUARD = "可怖的血肉磨盘"
--大煮锅
STRINGS.RECIPE_DESC.BUILDING_MIRACLECOOKPOT = "制作高级食物"
--空间锚定仪
STRINGS.RECIPE_DESC.BUILDING_SPATIALANCHOR = "锚定空间，选择传送"
--第一具现原理
STRINGS.RECIPE_DESC.BUILDING_MOONCIRLEFORM = "学会使用魔术"
--饰品作坊
STRINGS.RECIPE_DESC.BUILDING_TRINKETWORKSHOP = "制作饰品"
--炼金台
STRINGS.RECIPE_DESC.BUILDING_ALCHEMYDESK = "点石成金！"
--种子
STRINGS.RECIPE_DESC.PSIONIC_MOONSEED = "奇异种子。"
--灵液
STRINGS.RECIPE_DESC.PSIONIC_LIQUID = "从生物组织榨取的\n诡异液体"
--灵化土壤
STRINGS.RECIPE_DESC.PSIONIC_SOIL = "浸润灵液的土壤。"
--洗涤水
STRINGS.RECIPE_DESC.POTION_HOLYWATER = "洗濯被侵蚀的灵魂。"



--基础物品
STRINGS.NAMES.BASE_MOONGLASS = "月亮水晶"
STRINGS.NAMES.BASE_GEMFRAGMENT = "宝石碎片"
STRINGS.NAMES.BASE_MOONROCK_NUGGET = "月石"
STRINGS.NAMES.BASE_HORRORFUEL = "纯粹恐惧"
STRINGS.NAMES.BASE_PUREGEM = "纯粹宝石"
STRINGS.NAMES.BASE_MOONEMPYREALITY = "弥散月质"
STRINGS.NAMES.BASE_GEMBLOCK = "宝石块"
STRINGS.NAMES.BASE_PUREMOONEMPYREALITY = "纯粹月质"
STRINGS.NAMES.BASE_POLISHGEM = "打磨宝石"

--食物
STRINGS.NAMES.ARCUEID_FOOD_OMELETTERICE = "蛋包饭"
STRINGS.NAMES.ARCUEID_FOOD_TOFUSOUP = "豆腐汤"
STRINGS.NAMES.ARCUEID_FOOD_BERRYCAKE = "浆果蛋糕"
STRINGS.NAMES.ARCUEID_FOOD_TAKOYAKI = "章鱼烧"
STRINGS.NAMES.ARCUEID_FOOD_SHRIMPFRIEDRICE = "虾仁炒饭"
STRINGS.NAMES.ARCUEID_FOOD_SANDWICH = "三明治"
STRINGS.NAMES.ARCUEID_FOOD_PUFF = "泡芙"
STRINGS.NAMES.ARCUEID_FOOD_PIRI = "辣椒酱"
STRINGS.NAMES.ARCUEID_FOOD_PEPPER = "辣椒"
STRINGS.NAMES.ARCUEID_FOOD_MIXEDSOUP = "杂炖鲜汤"
STRINGS.NAMES.ARCUEID_FOOD_KETCHUP = "番茄酱"
STRINGS.NAMES.ARCUEID_FOOD_HOTDOG = "热狗"
STRINGS.NAMES.ARCUEID_FOOD_DOUGHNUT = "甜甜圈"
STRINGS.NAMES.ARCUEID_FOOD_CREAMHONEYCUT = "奶油蜂蜜切饼"
STRINGS.NAMES.ARCUEID_FOOD_CHOCOLATECOOKIES = "巧克力曲奇"
STRINGS.NAMES.ARCUEID_FOOD_BERRYEGGTART = "浆果蛋挞"

--装备
STRINGS.NAMES.DRESS_ICE = "身缠冰河"
STRINGS.NAMES.DRESS_REDMOON = "REDMOON"

--建筑
STRINGS.NAMES.ARCUEID_FAKEBEEBOX = "假蜂箱"
STRINGS.NAMES.BUILDING_GEMICEBOX = "魔术宝石冰箱"
STRINGS.NAMES.BUILDING_TRAVELLERBOX = "旅行者时空箱"
STRINGS.NAMES.TRAVELLERBOX_INV = "旅行者时空箱"
STRINGS.NAMES.BUILDING_IMMORTALLIGHT = "宝石魔术灯"
STRINGS.NAMES.BUILDING_GEMGENERATOR = "宝石发生器"
STRINGS.NAMES.BUILDING_ROTTENFORM = "腐败滋生术式"
STRINGS.NAMES.BUILDING_RECYCLEFORM = "第二分解术式"
STRINGS.NAMES.BUILDING_INFINITAS = "Infinitas箱"
STRINGS.NAMES.BUILDING_GUARD = "魔术炮塔"
STRINGS.NAMES.BUILDING_MIRACLECOOKPOT = "大煮锅"
STRINGS.NAMES.BUILDING_SPATIALANCHOR = "空间锚定塔"
STRINGS.NAMES.BUILDING_MOONCIRLEFORM = "第一具现原理"
STRINGS.NAMES.BUILDING_TRINKETWORKSHOP = "饰品作坊"
STRINGS.NAMES.BUILDING_ALCHEMYDESK = "炼金台"
STRINGS.NAMES.BUILDING_MOONDIAL = "映月台"
STRINGS.NAMES.BUILDING_ROOMBOX = "灵化木箱"

--动作
STRINGS.SHARPCLAW_EQUIP = "伸出"

--饰品
STRINGS.NAMES.TRINKET_MOONCLOAK = "月光斗篷"
STRINGS.NAMES.TRINKET_ETERNALLIGHT = "不灭烛"
STRINGS.NAMES.TRINKET_SHADOWCLOAK = "阴影斗篷"
STRINGS.NAMES.TRINKET_MOONAMULET = "月亮吊坠"
STRINGS.NAMES.TRINKET_SEASONINGBOTTLE = "亵渎调料瓶"
STRINGS.NAMES.TRINKET_ICECRYSTAL = "冰晶·立冬"
STRINGS.NAMES.TRINKET_JADESTAR = "翡翠星星"
STRINGS.NAMES.TRINKET_FIRSTCANON = "第一圣典"
STRINGS.NAMES.TRINKET_JADEBLADE = "翡翠之刃"
STRINGS.NAMES.TRINKET_MARTYRSEAL = "赴死者勋"
STRINGS.NAMES.TRINKET_SPIRITBOTTLE = "瓶中灵"
STRINGS.NAMES.TRINKET_TWELVEDICE = "十二面骰子"
STRINGS.NAMES.TRINKET_PROPHETEYE = "先知之眼"
STRINGS.NAMES.TRINKET_MOONWRISTBAND = "月亮护腕"
STRINGS.NAMES.TRINKET_MOONRING = "月亮指环"
STRINGS.NAMES.TRINKET_RELAXATIONBOOK = "休憩之书"
STRINGS.NAMES.TRINKET_SACRIFICEKNIFE = "献祭小刀"

--灵化
STRINGS.NAMES.BUILDING_PSIONIC_FARM = "灵化农场"
STRINGS.NAMES.PSIONIC_HOLYPETAL = "香夭花"
STRINGS.NAMES.PSIONIC_SOIL = "灵化土壤"
STRINGS.NAMES.PSIONIC_NORSOIL = "碎土"
STRINGS.NAMES.PSIONIC_LIQUID = "灵液"
STRINGS.NAMES.POTION_HOLYWATER = "洗涤水"
STRINGS.NAMES.PSIONIC_MOONSEED = "月化种子"
STRINGS.NAMES.PSIONIC_GORYPETAL = "血涎花"
STRINGS.NAMES.PSIONIC_THIRSTYFRUIT = "血嗜果"

--消耗品
STRINGS.NAMES.ARCUEID_CONSUME_LUCKYBAG = "恩赐的遗物"

--信封
STRINGS.LETTERCONTENT = {}
STRINGS.LETTERCONTENT.ID0_0 = ""
STRINGS.LETTERCONTENT.ID0_1 = ""
STRINGS.LETTERCONTENT.ID0_2 = ""
STRINGS.LETTERCONTENT.ID0_3 = ""
STRINGS.LETTERCONTENT.ID1_0 = ""



